#!/bin/bash
# Copyright (C) 2014 Alexander Keller <github@nycroth.com>

# Edited by Auto-Nom    -original i3blocks script wasn't working with my wifi
# /usr/share/i3blocks/wifi

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#------------------------------------------------------------------------

INTERFACE="${BLOCK_INSTANCE:-wlan0}"

#------------------------------------------------------------------------

# As per #36 -- It is transparent: e.g. if the machine has no battery or wireless
# connection (think desktop), the corresponding block should not be displayed.
[[ ! -d /sys/class/net/${INTERFACE}/wireless ]] ||
    [[ "$(cat /sys/class/net/$INTERFACE/operstate)" = 'down' ]] && exit

#------------------------------------------------------------------------
#                           <your SSID here> maybe grep -e '^*' then use line 2?
QUALITY=$(nmcli dev wifi | grep Slow-Internet | awk '{ print int($7) }')
BARS=$(nmcli dev wifi | grep Slow-Internet | awk '{ print $8 }')

#------------------------------------------------------------------------

echo " $BARS $QUALITY%" # full text
echo $QUALITY % # short text

# color
if [[ $QUALITY -ge 80 ]]; then
    echo "#00FF00"
elif [[ $QUALITY -ge 60 ]]; then
    echo "#FFF600"
elif [[ $QUALITY -ge 40 ]]; then
    echo "#FFAE00"
elif [[ $QUALITY -ge 20 ]]; then
    echo "#FF0000"
fi
